# Generated by Django 3.2.25 on 2024-11-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espaciocomun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioComunImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL de la Imagen')),
                ('texto_alternativo', models.CharField(help_text='Texto que describe la imagen para accesibilidad', max_length=255, verbose_name='Texto Alternativo')),
                ('espacio_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='espaciocomun.espaciocomun', verbose_name='Espacio Común')),
            ],
        ),
    ]
