# Generated by Django 3.2.25 on 2024-11-19 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espaciocomun', '0002_espaciocomunimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('POR_CONFIRMAR', 'Por Confirmar'), ('CONFIRMADA', 'Confirmada'), ('Finalazada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='POR_CONFIRMAR', max_length=15, verbose_name='Estado')),
                ('espacio_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='espaciocomun.espaciocomun', verbose_name='Espacio Común')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
